In [3]:
# Array Shape Manipulation 08-21-19[Wednesday]

import numpy as np

a = np.array([('Germany','France','Hungary','Austria'),('Berlin','Paris','Budapest','Vienna')])
a

array([['Germany', 'France', 'Hungary', 'Austria'],
       ['Berlin', 'Paris', 'Budapest', 'Vienna']], dtype='<U8')

In [4]:
a.shape

(2, 4)

In [5]:
a.ravel()

#Flatten is a method, but Ravel is a bultin function and can also  be used outside of an array

array(['Germany', 'France', 'Hungary', 'Austria', 'Berlin', 'Paris',
       'Budapest', 'Vienna'], dtype='<U8')

In [6]:
a.T

# Transpone is convertion of rows into col's or viceversa 

array([['Germany', 'Berlin'],
       ['France', 'Paris'],
       ['Hungary', 'Budapest'],
       ['Austria', 'Vienna']], dtype='<U8')

In [7]:
a.T.ravel()

#UTF Encoding and UTF Coding.

array(['Germany', 'Berlin', 'France', 'Paris', 'Hungary', 'Budapest',
       'Austria', 'Vienna'], dtype='<U8')

In [8]:
# Array Spliting

x=np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
print('Split the array in 3 equal-sized subarrays')
np.split(x,3)

Split the array in 3 equal-sized subarrays


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [11]:
y=np.arange(20)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
print('Split the array in equal-sized subarrays')
np.split(y,5)

Split the array in equal-sized subarrays


[array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([12, 13, 14, 15]),
 array([16, 17, 18, 19])]

In [15]:
print('Split the array in equal-sized subarrays')
np.split(y,4)

Split the array in equal-sized subarrays


[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19])]

In [17]:
print('Split the array in equal-sized subarrays')
np.split(y,10)

Split the array in equal-sized subarrays


[array([0, 1]),
 array([2, 3]),
 array([4, 5]),
 array([6, 7]),
 array([8, 9]),
 array([10, 11]),
 array([12, 13]),
 array([14, 15]),
 array([16, 17]),
 array([18, 19])]

In [18]:
print('Split the array in equal-sized subarrays')
np.split(y,20)

Split the array in equal-sized subarrays


[array([0]),
 array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([8]),
 array([9]),
 array([10]),
 array([11]),
 array([12]),
 array([13]),
 array([14]),
 array([15]),
 array([16]),
 array([17]),
 array([18]),
 array([19])]