In [9]:
# Numpy_Indexing_Slicing   08-14-15[Wednesday]

import numpy as np

a=np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
a=a**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [11]:
a[2]

4

In [12]:
a[-2]

81

In [13]:
a[2:7]

array([ 4,  9, 16, 25, 36])

In [14]:
a[2:-2]

array([ 4,  9, 16, 25, 36, 49, 64])

In [18]:
a[0:2]

array([0, 1])

In [19]:
a[2:]

array([  4,   9,  16,  25,  36,  49,  64,  81, 100])

In [20]:
a[:7]

array([ 0,  1,  4,  9, 16, 25, 36])

In [21]:
a[:11:2] #[start:stop:step]

array([  0,   4,  16,  36,  64, 100])

In [31]:
# How to pring array of numbers in a reverse order by using -ve indexing?
a[ : : -1]

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0])

In [32]:
a[0:11:-1]

array([], dtype=int64)

In [25]:
b=np.arange(1,6)
b

array([1, 2, 3, 4, 5])

In [26]:
b[0:4:2]

array([1, 3])

In [30]:
b[0:6:-1]

array([], dtype=int64)