In [1]:
#Python_Adv_Day2(Numpy_Array_Creation)

import numpy as np

array_of_ones = np.ones((3,4))
# 3 represents rows and 4 represents coloums
#(3,4) --> (x,y) --> X = no of rows  & Y = no of coloums
array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
# How to specify the data type???
# A) Use dtype function

array_of_ones_int = np.ones((3,4)),np.dtype(np.int16)
array_of_ones_int

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]), dtype('int16'))

In [19]:
# Declaring an empty array

array_empty = np.empty((2,3))
array_empty

#note: Array of zero & empty took similarly, but in empty you can change the values.


array([[4.67528725e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [20]:
# How to create an identity matrix?
# Use np.eye()

array_eye = np. eye(3)
array_eye

# it's called as eye (or) Identity matrix.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# range is a function in python.
# arange is a funtion in numpy.
# what is the sytnax of arange?
# arange(start value, stop value, Step value)
# Req: Print the list of even number till 20?


array_of_evens = np.arange(2,22,2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [22]:
# what is meant by built in function???
# It accepts the float arguments

array_of_float = np.arange(0,2,0.3)
array_of_float

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [28]:
# Introduction to two dimensional arrays:

import numpy as np

array_2d = np.array([(2,4,6),(3,5,7)])
array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [29]:
# how to verify above?

array_2d.shape

(2, 3)

In [35]:
# How to create n dimensional array???
# A) by using .reshape()

array_nd = np.arange(6).reshape(3,2)
array_nd

array([[0, 1],
       [2, 3],
       [4, 5]])

In [36]:
array_2nd = np.arange(12).reshape(6,2)
array_2nd

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])