In [ ]:
# Python_Adv_Day1 - 08-01-2019[Thursday]

# Numpy_Day1_Intro.

# Introduction to Numpy.

# Creating Arrays
# Printing Arrays
# Basic Operations
# Indexing & Slicing.
# How & When we will be using it...??
#                  like Data Analytics, Data Science fields,AI.. where data is involved...numpy will be there as underlying.


# Q) What exactly a Numpy is ??
# A) Numpy is a numerical computing package!!
# Note: Python cannot support the functionality what numpy provides directly.

# Q) What are all we be will working on...?
# A) Multi Dimentionsal data --NUMPY---ndarray...!! forms as a core scientific package.

# -- Supports wide variety of operation, ML Computations such as Linear Algebra, Random number capabilities etc...
# -- Basic building block of numpy is a poweful -n Dimensional array
# -- It forms the core of the python eco system, of open source s/w for maths,science & Engineering.
# -- Numpy forms the core of these things!!

In [1]:
# Steps to install numpy.
# Note: Jupyter will have numpy by default.

!pip install numpy

In [2]:
# Steps to upgrade numpy.

!pip install numpy --upgrade

    100% |████████████████████████████████| 20.3MB 779kB/s ta 0:00:011  4% |█▍                              | 870kB 5.0MB/s eta 0:00:04    71% |██████████████████████▊         | 14.5MB 1.7MB/s eta 0:00:04
tables 3.5.1 requires mock>=2.0, which is not installed.
  Found existing installation: numpy 1.16.2
    Uninstalling numpy-1.16.2:
      Successfully uninstalled numpy-1.16.2


In [3]:
# As per above numpy upgrade completed.
# To check current version of numpy, run the upgrade command.

!pip install numpy

In [4]:
import numpy as np
# As is used for alias names..simplicity in coding.
# Note: Any name can be used for alias.
# Commonly follwed alias
# numpy = np
# Pandas = pd

array_one = np.array([1,2,3,4])
array_one

array([1, 2, 3, 4])

In [5]:
numbers = [9,8,7,6]
array_two = np.array(numbers)
array_two

array([9, 8, 7, 6])

In [6]:
# **IMPT Array of Zeros

array_of_zeros = np.zeros((3,4))

# 3 is rows and 4 is columns.

array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])