In [6]:
#Python_Adv_Day4(Numpy_Day4)

import numpy as np
a=np.array([10,10,10])
b=np.array([5,5,5])

print('a+b=', a+b)
print('a-b=', a-b)
print('a*b=', a*b)
print('a/b=', a/b)
print('a%b=', a%b)


a+b= [15 15 15]
a-b= [5 5 5]
a*b= [50 50 50]
a/b= [2. 2. 2.]
a%b= [0 0 0]


In [7]:
a**2 
# It will do square of 

array([100, 100, 100])

In [8]:
# Dot function (or) method

A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

print ('A:\n', A)
print ('B:\n', B)

A:
 [[1 1]
 [0 1]]
B:
 [[2 0]
 [3 4]]


In [9]:
A*B # Element wise multiplication happen

array([[2, 0],
       [0, 4]])

In [10]:
A.dot(B) # Matrix multiplication

array([[5, 4],
       [3, 4]])

In [20]:
# Modifying an existing array rather than creating a new one.

a = np.array ([10,10,10])
b = np.array ([5,5,5])
a +=3
print(a)
b +=a
print(b)


[13 13 13]
[18 18 18]


In [25]:
# unary operations.
ages = np.array([12,15,18,20])
print('ages.sum =', ages.sum())
print('ages.min =', ages.min())
print('ages.max =', ages.max())

ages.sum = 65
ages.min = 12
ages.max = 20


In [27]:
numbers = np.arange(12).reshape(4,3)
numbers

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
numbers.sum()

66

In [30]:
# Aris - 0 --> Coloumn
# Aris - 1 --> Rows

numbers.sum(axis = 0)


array([18, 22, 26])

In [31]:
numbers.sum(axis = 1)

array([ 3, 12, 21, 30])

In [38]:
# Universal Functions : Trignometry, Arthamatic, Complex and Statistical Functions are called as Universal functions,
# Trignometric Functions:

angles = np.array([0,30,45,60,90])
# Angles need to be converted to radians by multiplying by pi/180
angles_radians = angles*np.pi/180
print (angles_radians)
print('SINE of angles in the array:')
print(np.sin(angles_radians))

print('\nTAN of angles in the array:')
print(np.tan(angles_radians))

print('\nCOS of angles in the array:')
print(np.cos(angles_radians))

[0.         0.52359878 0.78539816 1.04719755 1.57079633]
SINE of angles in the array:
[0.         0.5        0.70710678 0.8660254  1.        ]

TAN of angles in the array:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]

COS of angles in the array:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [39]:
# Statistical Functions:
test_scores = np.array([32.32, 56.98, 21.52, 44.32, 55.63])
print('\nMean Test Scores of the students:')
print(np.mean(test_scores))

print('\nMedian Test Scores of the students:')
print(np.median(test_scores))


Mean Test Scores of the students:
42.153999999999996

Median Test Scores of the students:
44.32


In [48]:
salaries = np.genfromtxt('/home/andhavarapu/SW-DUMP/python_advance/numpy_data_sets/salary.csv',delimiter= ",")
salaries

array([ 60000.,  58000.,  56967.,  54000.,  70000.,  39000.,  36000.,
        26000.,  43000.,  75000.,  41411.,  36000.,  26000.,  40000.,
        40000.,  62000.,  30000.,  22680.,  27600.,  44000.,  32400.,
        56000., 261546.,  40000.,  77000.,  30819.,  42000., 500000.,
        77570.,  60000.,  42000.,  65000.,  60000., 120000.,  54000.,
        46860.,  81000.,  75000.,  75000.,  35000.,  43000.,  40000.,
        73000.,  14134.,  75000., 210000.,  90000.,  38400., 105227.,
        84000.,  48000.,  55000.,  98000.,  50000.,  22000.,  70000.,
        36000.,  36000.,  42000., 115000.,  72000.,  50000.,  49000.,
        30000.,  48000.,  25000.,  42000.,  57400.,  70000.,  53000.,
        31000.,  46000.,  50000.,  45000.,  50000.,  71796.,  47000.,
       130773., 103529.,  57000.,  45000.,  70000.,  40000.,  75000.,
        57000.,  22000.,  30514., 119875.,  60000.,  32000.,  46860.,
       132000., 100000.,  22000., 141671.,  87500.,  90000.,  65000.,
        30514.,  274

In [47]:
import sys
np.set_printoptions(threshold = sys.maxsize)

In [52]:
print('\n Mean Salaries',np.mean(salaries))
print('\n Median Salaries',np.median(salaries))
print('\n', np.std(salaries))   # std --> standard deviations
print('\n', np.var(salaries))


 Mean Salaries 55894.53879686138

 Median Salaries 48000.0

 55170.37550939316

 3043770333.8474483
